//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuitionMedia_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public int QualificationId { get; set; }
        public string Degree { get; set; }
        public int PassingYear { get; set; }
        public string Result { get; set; }
        public string Institute { get; set; }
        public int Tutorid { get; set; }
    
        public virtual Tutor Tutor { get; set; }
    }
}
